# Generated by Django 6.0.6 on 2026-06-14 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0002_initial'),
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='importer.importbatch'),
        ),
    ]
